### ISSUE TITLE
Fee calculation incorrect

### ISSUE THREAD

**Issue by incognitojam** [langerhans/dogecoin-wallet-new#100]
From the dogecoin-help channel in the Dogecoin discord, reported by K4D3Gr8#1504.

![image](https://user-images.githubusercontent.com/4038174/118398653-72d37900-b651-11eb-94f0-1ebb637a4765.png)

**Comment by btc2doge** [comment]
did you choose the "empty wallet" choice to transfer all? when i choose empty wallet, i also met the similar problem. i found the fee is not 1 doge. when i send amount below the balance. it only charge 1 Doge fee. another problem is that it always keep the status "the payment has not been transmitted yet" after i reset the blockchain. it did not resolve it.  the solution is decrypt the backup and import the private key in core wallet to move your doge. another solution is try to send a mount below the balance each time. don't use the empty choice.  check the network monitor to make sure there is peers connected and blocks sync is updated before you make transfer. it is easy to get stuck without peers.

**Comment by btc2doge** [comment]
if you use the second solution, you can try to restore with backup to cancel current transfer or use the resetting the blocks following "setting--->diagnostics---> reset block chain' after sync again competed. your balance will recover and the current pending transfer will be cancelled and disappear.

**Comment by Dimastyjja** [comment]
> From the dogecoin-help channel in the Dogecoin discord, reported by K4D3Gr8#1504.
> 
> ![image](https://user-images.githubusercontent.com/4038174/118398653-72d37900-b651-11eb-94f0-1ebb637a4765.png)

**Comment by Dimastyjja** [comment]
> > Из канала dogecoin-help в разногласиях Dogecoin, сообщение K4D3Gr8 # 1504.
> > ![изображение](https://user-images.githubusercontent.com/4038174/118398653-72d37900-b651-11eb-94f0-1ebb637a4765.png)
