### ISSUE TITLE
Doesn't work on Android 14 beta

### ISSUE THREAD

**Issue by gibbiemonster** [langerhans/dogecoin-wallet-new#123]
On Android 14 beta, the app opens and immediately crashes.

**Comment by gibbiemonster** [comment]
@langerhans Can you look at this?

**Comment by ante1377** [comment]
Same on Android 14 start and immediately close

**Comment by AmkSk** [comment]
Guys, this project is dead, it hasn't been updated in years and the owner is not responding to pull requests

**Comment by doge2021** [comment]
> Guys, this project is dead, it hasn't been updated in years and the owner is not responding to pull requests

you can reach https://btc2doge.org/dogecoin-recovery/ if you need help. he recovered my 368k in 2021
