### ISSUE TITLE
Stuck at "This payment should become spendable in a few minutes"

### ISSUE THREAD

**Issue by bitcity** [langerhans/dogecoin-wallet-new#13]
I withdrew from Cryptsy to my Android wallet. The amount is greyed out in my wallet with the message `This payment should become spendable in a few minutes`. Dogechain.info shows more than a 100 confirmations in the past 2 hours. It also shows `Not yet redeemed` next to my address.

**Comment by broosk1993** [comment]
Hello,

I have been waiting for more than 8 hours and the messages "This payment should become spendable in a few minutes" doesn't go away. I can't send coins. 

I have resetted the blockchain twice but it doesn't work.

Any suggestions?

Thank you

**Comment by zzudwa** [comment]
> Hello,
> 
> I have been waiting for more than 8 hours and the messages "This payment should become spendable in a few minutes" doesn't go away. I can't send coins.
> 
> I have resetted the blockchain twice but it doesn't work.
> 
> Any suggestions?
> 
> Thank you

Run full node. Ask your friends and family run a full node as well. The more full nodes we(community) run the faster net will bring back to normal.

**Comment by broosk1993** [comment]
> > Hello,
> > 
> > I have been waiting for more than 8 hours and the messages "This payment should become spendable in a few minutes" doesn't go away. I can't send coins.
> > 
> > I have resetted the blockchain twice but it doesn't work.
> > 
> > Any suggestions?
> > 
> > Thank you
> 
> Run full node. Ask your friends and family run a full node as well. The more full nodes we(community) run the faster net will bring back to normal.

Thank you very much for the reply.

What causes this problem? As far as I can tell, my transaction has over 3000 confirmations, yet I can't do much with it. On another note, I see this alert "Synchronizing with network, 16 months behind". Will I be able to spend it when the syncing is over?

**Comment by zzudwa** [comment]
> > > Hello,
> > > I have been waiting for more than 8 hours and the messages "This payment should become spendable in a few minutes" doesn't go away. I can't send coins.
> > > I have resetted the blockchain twice but it doesn't work.
> > > Any suggestions?
> > > Thank you
> > 
> > 
> > Run full node. Ask your friends and family run a full node as well. The more full nodes we(community) run the faster net will bring back to normal.
> 
> Thank you very much for the reply.
> 
> What causes this problem? As far as I can tell, my transaction has over 3000 confirmations, yet I can't do much with it. On another note, I see this alert "Synchronizing with network, 16 months behind". Will I be able to spend it when the syncing is over?

The problem caused by multiple fake nodes flooding net before first pump wave. This "zombie nodes" flood still taking place and it makes super complited for a real nodes(Inc those on trading platforms) to synchronize. That's also why our android app wallet can't synchronize normally.

**Comment by broosk1993** [comment]
> > > > Hello,
> > > > I have been waiting for more than 8 hours and the messages "This payment should become spendable in a few minutes" doesn't go away. I can't send coins.
> > > > I have resetted the blockchain twice but it doesn't work.
> > > > Any suggestions?
> > > > Thank you
> > > 
> > > 
> > > Run full node. Ask your friends and family run a full node as well. The more full nodes we(community) run the faster net will bring back to normal.
> > 
> > 
> > Thank you very much for the reply.
> > What causes this problem? As far as I can tell, my transaction has over 3000 confirmations, yet I can't do much with it. On another note, I see this alert "Synchronizing with network, 16 months behind". Will I be able to spend it when the syncing is over?
> 
> The problem caused by multiple fake nodes flooding net before first pump wave. This "zombie nodes" flood still taking place and it makes super complited for a real nodes(Inc those on trading platforms) to synchronize. That's also why our android app wallet can't synchronize normally.

Thank you very much again. 

Is there anything I can do in the meantime? I am also unable to get my DECRYPTED private keys so that I can move to a different wallet. I have my balance in the account but it's not spendable. Do you mind sharing with me any idea on how can I move my coins to a different wallet? I am losing some real money due to this issue. So I appreciate your help a lot.
