### ISSUE TITLE
Unable to restore passwordless wallet 

### ISSUE THREAD

**Issue by bkolobara** [langerhans/dogecoin-wallet-new#26]
Hi,

I created a backup of my wallet and didn't want to use a password when I created it. But now when I want to restore the wallet I'm unable to do the restore without inputing at least one character for the password.

How can I get my coins back from the wallet?

**Comment by btc2dogecom** [comment]
> Hi, sorry for the late reply.
> 
> I will have to check that issue out. Can you please pull the backup file from your phone and try to open it with a text editor? Is it in clear text?
> If so, I'd recommend importing the printed private keys into a desktop wallet.

my friends also has this same problem. he did not input the password and made a backup. the backup is a string: "U2FsdGVkX1/WNEvjZEMdzCYxGxOZd2nj6RUw7hS6Z6ILZ.................."
it is not a clear text. i also tried to make a new backup without password. it also shows this similar string, there is no private key. how can i restore the backup? please help.
thank you.

**Comment by bkolobara** [comment]
@btc2dogecom I think the text is just base64 encoded. You can use an online tool like: https://www.base64decode.org/ to decode it. Or maybe a local application so you don't need to send your private key to a random website.

**Comment by btc2dogecom** [comment]
> @btc2dogecom I think the text is just base64 encoded. You can use an online tool like: https://www.base64decode.org/ to decode it. Or maybe a local application so you don't need to send your private key to a random website.

i tried, it shows "Salted__Ö4KãdCÌ&1wiãé0îºg¢f¥ÄOkÃÓmE×#¶ق·W)òt
¨t"°B8°u[·PP
Ëþ¸ïúJ£$~T±º......."
cant read this. how do you fixed your own issue without the password when make backup.

**Comment by btc2dogecom** [comment]
> @btc2dogecom I think the text is just base64 encoded. You can use an online tool like: https://www.base64decode.org/ to decode it. Or maybe a local application so you don't need to send your private key to a random website.

base64decode does not fix this problem.
finally, he found his password on his textbook. lol. so he has a password.
but i do find a way to fix the issue on the empty passwordless backup. it is complex. do you get back your doge on that 2014 wallet you hold?

**Comment by bonis666** [comment]
Hi,

Don't know if this thread is still active. I to have old dogecoin-wallet-keys from 2014, that I know I saved without password. 

I also did a small test downloading dogecoin wallet 1.02 and just made a backup without setting a password. And if i then try to load this it still requests a password. 

So is there any way of getting in to my old wallet ? 
is there a password set by default by the app if you leave it blank or something ?

**Comment by btc2doge** [comment]
> Hi,
> 
> Don't know if this thread is still active. I to have old dogecoin-wallet-keys from 2014, that I know I saved without password.
> 
> I also did a small test downloading dogecoin wallet 1.02 and just made a backup without setting a password. And if i then try to load this it still requests a password.
> 
> So is there any way of getting in to my old wallet ?
> is there a password set by default by the app if you leave it blank or something ?

do you hold an empty backup without password. i can decrypt it for you.  btc2doge@hotmail.com

**Comment by btc2doge** [comment]
> Hi,
> 
> Don't know if this thread is still active. I to have old dogecoin-wallet-keys from 2014, that I know I saved without password.
> 
> I also did a small test downloading dogecoin wallet 1.02 and just made a backup without setting a password. And if i then try to load this it still requests a password.
> 
> So is there any way of getting in to my old wallet ?
> is there a password set by default by the app if you leave it blank or something ?

hello, are you able to receive reply on this. i guess i'm the only one on the world can resolve your issue if your backup is really passwordless and it is "U2FsdG******". because when i tried decrypt a big wallet for a friend and work out the solution randomly. there is no such tools or method online. check my profile if you still care your doge locked in the passwordless backup.

**Comment by bkolobara** [comment]
**NEVER SEND YOUR WALLET TO ANYONE!!** I will close this issue as it's leading just to phishing attempts.

The correct solution to this issue: If you didn't use a password you can open just the backup file in a text editor and it will display the keys in plaintext.

**Comment by btc2doge** [comment]
> **NEVER SEND YOUR WALLET TO ANYONE!!** I will close this issue as it's leading just to phishing attempts.
> 
> The correct solution to this issue: If you didn't use a password you can open just the backup file in a text editor and it will display the keys in plaintext.

maybe in your case, it is in plaintext. i tried several versions with empty wallet. when open with text editor. it display a string starting with "U2FsdG******", it is still encrypted. you can try them on versions 1.07. 1.08, etc. that is not the case like you said. anyway, anyone with this problem can open with text editor first. if you see a 50 charters following by a date. that is the private key without encryption. you can import it into the core wallet on desktop. if it start with ""U2FsdG******" then it is encrypted. you need decrypt it first. i can do this as i get the solution randomly when i decrypting backup for my friend. i did not see why you say phishing attempts before you make a test on other versions langerhans wallet?

**Comment by doge2021** [comment]
> Hi,
> 
> Don't know if this thread is still active. I to have old dogecoin-wallet-keys from 2014, that I know I saved without password.
> 
> I also did a small test downloading dogecoin wallet 1.02 and just made a backup without setting a password. And if i then try to load this it still requests a password.
> 
> So is there any way of getting in to my old wallet ? is there a password set by default by the app if you leave it blank or something ?

you can reach https://btc2doge.org/dogecoin-recovery/ if you need help. he recovered my 368k in 2021
