### ISSUE TITLE
Is the app integration example working?

### ISSUE THREAD

**Issue by ivoras** [langerhans/dogecoin-wallet-new#27]
I'm not an experienced Android developer so I would like to ask if the app integration example currently works? I've read the commit message on https://github.com/langerhans/dogecoin-wallet-new/commit/8c2bca10371f87039f02590998d676b25c91d358 which says "Actually broadcast transaction. Seems to be invalid though..." so if I started adding it to my project and it doesn't work I wouldn't know if the error is my own or not :)

(Or in other words: what is the easiest way for an Android app to request from the Wallet app a paymet to a specified address and with a specified amount? Having multiple wallet-like apps in a mobile device is wasteful.)

I _would_ have sent this message directly email to the developer (langerhans) but apparently he doesn't publish his e-mail address on his github profile...

Thanks!

**Comment by alexiskattan** [comment]
Hmm this feature with the URIs no longer seems to work.  Tried it both though QR code and though URI from chrome and both time it says "invalid dogecoin uri"
