### ISSUE TITLE
Origin of libscrypt.so

### ISSUE THREAD

**Issue by afwang** [langerhans/dogecoin-wallet-new#31]
Hey again. I've been looking into the Android NDK to begin understanding what needs to be done for acceptance into F-Droid. I'm wondering where the libscrypt libraries came from exactly.

**Comment by langerhans** [comment]
The Java and native implementation come both from here: https://github.com/wg/scrypt

**Comment by afwang** [comment]
Cool! Thanks! Will start digging around.
