### ISSUE TITLE
How to get private key

### ISSUE THREAD

**Issue by NamPNQ** [langerhans/dogecoin-wallet-new#33]
I want to import my wallet to online acc
https://my.dogechain.info/#/overview

And i need private key, can you help me?

**Comment by langerhans** [comment]
There is no point in exporting the private key if you want to move your coins. Send a normal transaction to your new wallet. 
There isn't even a function for it in the wallet but if you want to go through the whole process of "recovering" your coins, read this: https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/README.recover

**Comment by NamPNQ** [comment]
thank you :D

2015-12-11 14:47 GMT+07:00 Max K. <notifications@github.com>:

> There is no point in exporting the private key if you want to move your
> coins. Send a normal transaction to your new wallet.
> There isn't even a function for it in the wallet but if you want to go
> through the whole process of "recovering" your coins, read this:
> https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/README.recover
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langerhans/dogecoin-wallet-new/issues/33#issuecomment-163867151>
> .
>



-- 
*Trí tưởng tượng quan trọng hơn kiến thức.*
*__Albert Einstein__*
[image: photo]
*Phạm Ngọc Quang Nam*
Developer
m:0169.22.23.24.9 | e:nampnq@gmail.com | w:http://www.nampnq.cf
<https://www.facebook.com/nampnq>  <http://www.linkedin.com/in/nampnq>
<https://twitter.com/nampnq>  <https://plus.google.com/+NamPhamNgocQuang/>
