### ISSUE TITLE
not received coin 

### ISSUE THREAD

**Issue by mtad2002** [langerhans/dogecoin-wallet-new#41]
hi
i`ve transferred some coin to the wallet`s first generated address ,
the coin transferred successfully but it didn`t showed up in my wallet .
then i have tried to export my private key so that i can import it in another wallet
but its encrypted i can not open it.
can you tell me how can i get my private key ?

**Comment by langerhans** [comment]
There is some info here: https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/README.recover
You might need libdohj to get wallet-tool tho. Generally not receiving coins means your chain isn't even fully synced yet. Not really a wallet issue.
