### ISSUE TITLE
Regarding Android backup and restore

### ISSUE THREAD

**Issue by cdestiny** [langerhans/dogecoin-wallet-new#43]
Hi,

My asus zenfone 4 was unable to boot after the kitkat update. I had to flash the phone and all the data gone..... my dogecoin wallet is gone without backup as well. I tried to use dr. fone software to recover the data but i can only search some zip file( i didnt purchase the software yet hence cant restore to check what is the file content).

My last resort is android native google data/contact backup.....  do you think i could restore my wallet file from there? When i opened dogecoin-wallet just now, it is showing 0..... which i am going to knock my head to wall soon.

thanks....

**Comment by langerhans** [comment]
Android cloud backup is disabled for security reasons: https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/AndroidManifest.xml#L54
You shouldn't send your private keys off into some cloud you can't control ;) Closing here as it's not a wallet issue, but feel free to reply if you need any other assistance.
