### ISSUE TITLE
the 1.08 version Mobile wallet can't back up into the 3.0 version mobile. 

### ISSUE THREAD

**Issue by CodeCanFly** [langerhans/dogecoin-wallet-new#44]
the 1.08 version Mobile wallet can't back up into the 3.0 version mobile. the App error and back to the desktop

**Comment by btc2dogecom** [comment]
contact us to fix it: www.btc2doge.com

**Comment by doge2021** [comment]
you can reach https://btc2doge.org/dogecoin-recovery/ if you need help. he recovered my 368k in 2021
