### ISSUE TITLE
Need help transferred to request coins wallet address and not actual wallet address 

### ISSUE THREAD

**Issue by Kirankumar-kulkarni** [langerhans/dogecoin-wallet-new#47]
Hi,

I have transferred my Doge coins to this address (https://bitinfocharts.com/dogecoin/address/DGqiFMRWEqzJNp1QvVYoysVPYDHeeC5UBh#) by converting lite coin to Doge coin. This was displayed when I clicked request coins on Android app. Later I uninstalled the app thinking it is fraud. Now how can get back my Doge coins. I again installed the app.

**Comment by langerhans** [comment]
Uninstalling an Android app deletes all its data, so if you didn't make a backup you're out of luck. Sorry. Otherwise restore your backup and wait for it to sync,
