### ISSUE TITLE
Key to app

### ISSUE THREAD

**Issue by Khg2021** [langerhans/dogecoin-wallet-new#69]
Hi all,
I used to have in 2018 the wallet on my mobile. As I dont have it any more, I have only the Private keys of the wallet, is it possible to add those keys to the wallet again🤔? 

Thx

**Comment by Khg2021** [comment]
Sorry just found out that its not the PK that i have its the doge address... Nevertheless is there a vhance to get access back?

**Comment by langerhans** [comment]
Check #68

**Comment by btc2dogecom** [comment]
we can dig more info from your case. there is chance to recover it
contact us: btc2doge.com
