### ISSUE TITLE
This payment has not been transmitted yet

### ISSUE THREAD

**Issue by dumotica** [langerhans/dogecoin-wallet-new#70]
Hello Goodnight.

I have tried to make a payment to another wallet and it takes a long time, several hours, with that message and my doge to 0. Have I lost all my dogecoin? Greetings and thanks

**Comment by SikoSoft** [comment]
Same here.

Pretty sure this project is abandoned judging by the state of the app.

Buggy as hell, can't even maintain a connection to the network for more than a minute, if it can even make one. Blocks don't update... Over a day waiting and no progress at all. Remains the same amount of time behind the network no matter how many hours waited.

Backing up wallet doesn't include an address that money was just swept to.

At this point, I'd say this wallet is broken beyond use. It just ate 10k from me.

I used external tools to extract the private keys (which this app doesn't even give you the ability to do) from the wallet backup, plugged those into a wallet generator and see the address a sweep moved coins to isn't in the backup.

The backup also indicated "testnet" in the subject.

You're not alone dude. With any luck, Google will remove this app from the store with enough complaints. It's clearly not usable or trustworthy anymore.

**Comment by dumotica** [comment]
so i lost 6000 dogecoins ...

**Comment by SikoSoft** [comment]
Possibly, sadly. :(

If anything turns around for you please update. I've waited about 16 hours now and seen no progress, so it seems like I'm out 10,000 at moment as well.

The most infuriating thing about it all is the damn wallet backup isn't even working correctly. I had hoped I could just bail out of this mess and take my private keys elsewhere, but the backup doesn't contain the address it swept to.

**Comment by langerhans** [comment]
@SikoSoft I'd appreciate if you would not spread FUD. The dogecoin network as a whole is not overly healthy right now. This has nothing to do with this app.

**Comment by dumotica** [comment]
Why did the thread close?

**Comment by langerhans** [comment]
Because it's a duplicate. Before you open issues, check the others.

**Comment by dumotica** [comment]
Could you tell me what the duplicate is? I can't find it anywhere. regards

**Comment by nogasgofast** [comment]
You'll probably want to just give it time dumontica. I have found that the network seems over-saturated with transfers right now. You'll want to keep your app open as often and for long as possible to give it the largest number of chances to connect to a peer that can transmit for you. 

I've also noticed if your behind and the blocks don't seem to be updating. closing the app. Waiting a few seconds for it to shut down and then re-starting it will flush your peers and *sometimes* connect you to a node that is less saturated then the last set. And start the blocks flowing again on the app. Of coarse only do that if you have a set of 5+ peers and it's been 5 or more minutes since the last block update.

**Comment by dumotica** [comment]
Hi there,
Thanks for responding, I have tried several times to close and open the application and nothing, since January 29 the status is "This payment has not yet been processed". regards

**Comment by nogasgofast** [comment]
I was having the exact same problem as you here. 

I tried backing up, then re-installing the application. But that just reset the blockchain and now I am stuck waiting for it to catch back up. 

It's been a few days. I set my own dogecoin full-node up to be a Trusted peer. And set the "skip regular peer discovery" option so the phone would only connect to a known good peer. That did not work, I found the node I have is very busy. It's maxed out it's connections. So I ended up turning off "skip regular peer discovery" and that allowed the phone to connect to more peers. 
Which in turn sometimes end up connecting to fast peers that just happened to not be busy at the time.  I am back up to 2020 on the block chain after a day of ensuring it's always connected to at least some good peers or restarting the app. 

So I'll re-try my transaction or let you know if it's still stuck there after it catches up. Of if I get a transaction to work.

**Comment by dumotica** [comment]
I'll keep you posted if I get the transaction done.
Greetings and thanks.

**Comment by dumotica** [comment]
Hello, my transaction has just been done, I have not had to do anything else, it has synchronized itself, I hope you have luck with yours.
regards

**Comment by btc2doge** [comment]
> Possibly, sadly. :(
> 
> If anything turns around for you please update. I've waited about 16 hours now and seen no progress, so it seems like I'm out 10,000 at moment as well.
> 
> The most infuriating thing about it all is the damn wallet backup isn't even working correctly. I had hoped I could just bail out of this mess and take my private keys elsewhere, but the backup doesn't contain the address it swept to.

can help you fix it if you still have not recover your doge.
