### ISSUE TITLE
Dogecoin not spendable

### ISSUE THREAD

**Issue by kolossus10** [langerhans/dogecoin-wallet-new#71]
I can't seem to spend the dogecoin in the app. Saying "Not enough available coins. You're missing DOGE XXXX.XX. This may also be due to the network fee." Though I can see the dogecoin I've set to the wallet app is already reflecting. 

Any help?

**Comment by langerhans** [comment]
The wallet can't spend coins that are not confirmed yet. You need to wait for it to sync.
