### ISSUE TITLE
-

### ISSUE THREAD

**Issue by bruidbarrett** [langerhans/dogecoin-wallet-new#76]
-

**Comment by shibe2** [comment]
Optionally make another backup now. Than restore from your old backup.

**Comment by bruidbarrett** [comment]
The back up would already have the spending PIN on it as the original android device has a spending PIN on it right? I do not have any backups that do not have the spending PIN already on them

**Comment by shibe2** [comment]
So, did you try it? If not, it's worth trying.

**Comment by btc2dogecom** [comment]
> The back up would already have the spending PIN on it as the original android device has a spending PIN on it right? I do not have any backups that do not have the spending PIN already on them

do you have the oldest backup? the earliest version of backup?  check www.btc2doge.com

**Comment by cryptoprogramer** [comment]
> 
> 
> Hello, I have some absurd amount of dogecoin on the Langerhans Dogecoin Wallet and do not have access to my spending PIN, nor do I remember setting it but after searching through the code and previous issues, I don't believe it would set itself. If there is any way a dev or @langerhans could help me recover these funds, I have the original device and wallet backup/pass and am so desperate from some help from the original dev(s) to recover these ideally without bruiting it because I do not have the knowledge to do so.
> 
> **This is very important to me and I know you are all very busy, I would be very appreciative of any amounts of help you can give me!**
> 
> Looking forward to any help,
> 
> Tristan Barrett [bruidbarrett@gmail.com](mailto:bruidbarrett@gmail.com) landshark#6638

hi, I have recovered spending pin before. i can help you to gain access to your wallet
