### ISSUE TITLE
This payment has not been transmitted yet

### ISSUE THREAD

**Issue by MohammedAlasaad** [langerhans/dogecoin-wallet-new#77]
Hi
I have an issue with dogecoin wallet. I have sent 1990 coin to dogechain.info and worked fine.. Then I tried to send 40000 to same address and got **"This payment has not been transmitted yet"** and took long time ... I read online and saw ppl say do reset blockchain.. I did reset blockchain all transactions disappeared now!! and balance doge 0 and sync with network 20 months behind!!!
I did not get the transaction on my dogechain.info wallet!   What should I do???

**Comment by sinyob** [comment]
> Hi
> I have an issue with dogecoin wallet. I have sent 1990 coin to dogechain.info and worked fine.. Then I tried to send 40000 to same address and got **"This payment has not been transmitted yet"** and took long time ... I read online and saw ppl say do reset blockchain.. I did reset blockchain all transactions disappeared now!! and balance doge 0 and sync with network 20 months behind!!!
> I did not get the transaction on my dogechain.info wallet! What should I do???

Iwill help you, contact bambang9entolet@gmail.com

**Comment by Ranpuma** [comment]
I am having the same issue. I tried to send some coins but they did not transmit for a week. I had already backup my wallet and I tried to send and then the dogecoins went to 0 and it did not have a transaction history. Can I restore my coins?

**Comment by Dogefriend** [comment]
My wallet is showing 0.00 and the App created like 5 other wallets. How can I chose the one I've sent the Coins on? Or how can I delete the ones which are empty? Synchronization is failing for over 20 months. What on earth does that mean?! 

This is happening to so many people. Looks suspicious and I lost money because of all these issues. People will get very angry to the developers and even to Elon Musk. That's not good and we need a solution ASAP!

**Comment by MohammedAlasaad** [comment]
Thank you @sinyob
I have got my coins back finally. I know the app not scam but its really bad!.. IT SHOULD BE REMOVED FROM PLAY STORE or developer fix it.
I found a good way to move my coins to another wallet called Coinomi wallet, really great wallet and super fast!.
You can find the way here
https://www.reddit.com/r/dogecoin/comments/l8bu20/to_everyone_using_the_android_wallet_who_still/

**Comment by btc2dogecom** [comment]
> I am having the same issue. I tried to send some coins but they did not transmit for a week. I had already backup my wallet and I tried to send and then the dogecoins went to 0 and it did not have a transaction history. Can I restore my coins?
contact us if you did not fix it.  www.btc2doge.com
