### ISSUE TITLE
Issue with a password by importing the .key file

### ISSUE THREAD

**Issue by homezp** [langerhans/dogecoin-wallet-new#99]
Hello guys,
I want to import my wallet from multidoge into the dogecoin wallet on Android, and I have some trouble with this)
I have exported the .key file from the multidoge without setting a password, but I can't back-up it in DC-Wallet on Android, because a confirmation button is inactive, when no symbols are in the password field... I have tried to export it with a password, but DC-Wallet show me an error message (I have read about it, that another wallets can't import .key files with a password from multidoge) That's why I need to import it without a password, but DC-Wallet doesn't allow me to do this and wait for some password... :)
Can somebody help me with this?
Thanks in advance and best regards!

**Comment by btc2doge** [comment]
dogecoin android wallet and multidoge wallet keys are in different forms. you may not share the key between them. the easy way is to transfer you coins from multidoge to doge android.

**Comment by homezp** [comment]
> dogecoin android wallet and multidoge wallet keys are in different forms. you may not share the key between them. the easy way is to transfer you coins from multidoge to doge androi

**Comment by homezp** [comment]
Oh... I have afraid of this...
But OK, thank you for reply!

**Comment by doge2021** [comment]
i have the simiar problem as i did not set a password when make backup. while the Dogecoin android wallet ask for a password. finally i found a guy by google. you can reach stephen from  btc2doge.com. he can decrpty the passwordless wallet backup and get private key. but for your case, why not transfer the coins to your andriod wallet directly?

**Comment by homezp** [comment]
I have issues with a wallet synchronisation... There is "no" DC in the wallet, but I saw a transaction report and know, that it was succsesful. I have tried many times reload the transaction chains, but it takes so many time and without any result... The wallet show me "0"... That's why I wanted to try in anather wallet-program to finaly get DC on to the wallet =)

**Comment by doge2021** [comment]
> I have issues with a wallet synchronisation... There is "no" DC in the wallet, but I saw a transaction report and know, that it was succsesful. I have tried many times reload the transaction chains, but it takes so many time and without any result... The wallet show me "0"... That's why I wanted to try in anather wallet-program to finaly get DC on to the wallet =)

if so, i guess there is chance your doge moved to the change address. there is bug in early versions. you may decrypt the wallet backup to get privatekey then check if the doge still in wallet backup. there are several cases lost doge due to this. you may get help from stephen of btc2doge.com. he just helped decrypted my wallet without a password on android. refer my name, you can get 10% discount for the tip. good luck.
